Добавить импорт из базы данных
LeKaitoW/raox pull request #579
Opened 2017-09-09 08:59 UTC by mikhailmineev

2017-09-10 13:55 UTC, aurusov commented
Реквест уже смотреть ?

2017-09-10 16:25 UTC, mikhailmineev commented
Можно, но я ещё не настроил генерацию кода из querydsl

2017-09-10 16:30 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/persistence/RaoEntityManager.java
> +				Thread.currentThread().setContextClassLoader(loadedClasses.get(0).getClassLoader());
По поводу данной штуки, я пока не понимаю, почему данное решение https://stackoverflow.com/questions/27304580/mapping-entities-from-outside-classpath-loaded-dynamically  работает
Тут я беру один из классов, что объявляется в модели

2017-09-10 16:36 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/ModelInternalsParser.java
> +		Class.forName("service.PartService", true, classLoader);
Временно инициализирую классы своей модели здесь вручную, как исправить, пока два варианта
1. Быстрый, описывать имя класса в модели, и тут их все инициализировать, исправлю пока на такой вариант добавлю
2. По мне более грамотный, когда добавлю в rao типы данных datasource и domainmodel их можно будет инициализировать, как и остальные классы в данном файле

2017-09-10 18:36 UTC, aurusov commented on ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/persistence/RaoEntityManager.java
> +				Thread.currentThread().setContextClassLoader(loadedClasses.get(0).getClassLoader());
Видимо, у новых тредов не настроен ClassLoader.

2017-09-10 18:38 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/ModelInternalsParser.java
> +		Class.forName("service.PartService", true, classLoader);
Лучше сразу делать (2), а сейчас использовать костыль.

2017-09-30 19:08 UTC, aurusov commented on ru.bmstu.rk9.rao.lib/thirdparty/mysql/LICENSE.txt
> +MySQL Connector/J 5.1.44
Увы, но мы не можем использовать gpl2 с лицензией mit.

2017-09-30 19:11 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildJobProvider.java
> +						recentProject.build(IncrementalProjectBuilder.FULL_BUILD, monitor);
Вместо TODO надо завести методы с читаемыми названиями

2017-09-30 19:12 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			// ранее
Комментарии зло.

2017-09-30 19:14 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +					+ project.getName();
Это автоматическое форматирование ?

2017-09-30 19:15 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +	 */
Комменты удалить. Метод - копипаста ?

2017-10-01 08:15 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +					+ project.getName();
Да

2017-10-01 13:03 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.lib/thirdparty/mysql/LICENSE.txt
> +MySQL Connector/J 5.1.44
Тогда тут остается пользователю скачивать нужный коннектор со стороны и уже вручную добавлять в модель, данную фичу уже смог реализовать.
И тогда у меня вопрос, могу ли я затащить этот коннектор в репозиторий raox-models? Например в эту папку https://github.com/mikhailmineev/raox-models/tree/095e610f32c388180cbf24c6aeb50c16e5a59299/delivery_to_order
(или создать папку lib), чтобы на каждом компе себе не скачивать этот коннектор.

2017-10-01 16:26 UTC, aurusov commented on ru.bmstu.rk9.rao.lib/thirdparty/mysql/LICENSE.txt
> +MySQL Connector/J 5.1.44
Нет. Мы используем в raox-models одну из по настоящему свободную лицензию - MIT. GPL с ней несовместима.

2017-10-01 16:35 UTC, aurusov commented on ru.bmstu.rk9.rao.lib/thirdparty/mysql/LICENSE.txt
> +MySQL Connector/J 5.1.44
Посмотрел совместимость https://www.gnu.org/licenses/license-list.ru.html. Понятно, что в GPL-коде можно использовать MIT-код. Но вот чтобы наоборот - не уверен.

2017-10-01 16:47 UTC, aurusov commented on ru.bmstu.rk9.rao.lib/thirdparty/mysql/LICENSE.txt
> +MySQL Connector/J 5.1.44
Вот [тут](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#WhatDoesCompatMean) написано
`Это значит, что эта лицензия и GNU GPL совместимы; вы можете комбинировать текст, выпущенный по этой лицензии, с текстом, выпущенным по GNU GPL, в одной более крупной программе.`

По ссылке выше про MIT сказано
`Это безвольная неограничительная лицензия свободных программ без авторского лева, совместимая с GNU GPL. Иногда на нее неоднозначно ссылаются как на “Лицензию MIT”.`

Получается я зря тебя сбаламутил. Продолжаем использовать библиотеку под GPL.

2017-10-02 09:12 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		recursiveFindFiles(resources, root, ResourcesPlugin.getWorkspace().getRoot(), "java");
Вижу копипасты с кодом выше. Эти строчки можно обернуть во что-то типа `getJavaFiles()`.

2017-10-02 09:13 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			logger.debug("Loaded class " + className);
Я правильно понимаю, что тут кроме логирования ничего нет ?

2017-10-02 09:13 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			Class.forName(className, true, classLoader);
А это зачем ?

2017-10-02 09:15 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			String className = relative.replace(".java", "").replace('/', '.');
Тоже копипаста. Не вижу простого решения как убрать.

2017-10-02 09:16 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
>  	static boolean generateQueryDslCode(IProject project, ClassLoader classLoader)
Напомни, зачем этот метод, когда есть предыдущий ?

2017-10-02 10:15 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			logger.debug("Loaded class " + className);
Я логгер сунул для отладки, чтобы удостовериться, что нужные классы инициализируются, сейчас могу убрать, в нем уже нет надобности

2017-10-02 10:40 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			logger.debug("Loaded class " + className);
Так тут же не только логгер лишний, но и весь цикл. Или тебе исключение из `Class.forName()` важно ?

2017-10-02 12:05 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			logger.debug("Loaded class " + className);
Тут на самом деле весь метод не нужен, `loadQueryDslClasses` также инициализирует эти классы. А исключения `ClassNotFoundException` при нормальной работе не должно быть

2017-10-04 19:52 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +			logger.debug("Loaded class " + className);
Тогда удаляй, чтобы не мешался.

2017-11-16 19:56 UTC, aurusov commented
@mikhailmineev 
Миша, тревис ругается на сборку через мавен. Надо добавить новые либы в конфиги. Обратись за помощью к Леше.

@AlexChernov 
Леша, тревис ругается. Помоги Мише его зачинить.

2017-11-16 19:57 UTC, aurusov commented on ru.bmstu.rk9.rao.lib/.classpath
> +	<classpathentry exported="true" kind="lib" path="thirdparty/mysql/lib/mysql-connector-java-5.1.44-bin.jar"/>
Ты же хотел это хранить с моделью, а не кодом ?

2017-11-16 21:03 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildJobProvider.java
> +				updateValidationMarkers(file, loadedResource, monitor);
Есть прогресс в понимании цепочки компиляции, которую обсуждали голосом ?

2017-11-16 21:05 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		IPath root = project.getFolder("java").getLocation();
Напомни, это в первую очередь для классов работы с данными ? Ведь остальные классы можем располагать где угодно ?

2017-11-16 21:14 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/console/ConsoleView.java
> +							synchronized (lock) {
Я еще готов понять, зачем два раза используется `lock`. Но зачем нужен `waiting` ? Разве первого lock'а недостаточно ? Почему ты решил вообще не заходить в метод. Ведь так можно потерять данные.

2017-11-16 21:14 UTC, AlexChernov commented
[ERROR]   Missing requirement: ru.bmstu.rk9.rao 3.9.0.27-g378ff03 requires 'bundle ru.bmstu.rk9.rao.querydsl 4.1.3' but it could not be found

Локально мавеном собирается?

2017-11-16 21:39 UTC, AlexChernov reviewed
Minor:
По готовности кода, сделать rebase на release/current причесать историю коммитов, убрать пулы из мастера в ветку и т д. Текущий пулл реквест можно будет закрыть без подливания в мастер

2017-11-16 21:43 UTC, AlexChernov requested changes
Minor: Возможно я вне контекста, но  ad25c30d085d294edee6e740832feee8620bd122 выглядит как коммит, который надо сделать в отдельную ветку и ревьювить в отдельном пул-реквесте

2017-11-16 21:55 UTC, aurusov commented
>Minor: Возможно я вне контекста, но ad25c30 выглядит как коммит, который надо сделать в отдельную ветку и ревьювить в отдельном пул-реквесте

Всё так. Решили голосом так сделать.

2017-11-16 21:55 UTC, aurusov commented
>Я немного вне контекста, почему ru.bmstu.rk9.rao отдельный плагин, да еще и со своей версией?

Вот тут я не знаю. Кажется, так было всегда.

>Мавен ждет до субботы можем голосом обсудить?

Да.

2017-11-16 21:57 UTC, aurusov commented
>Текущий пулл реквест можно будет закрыть без подливания в мастер

Не понял концовку.

2017-11-17 09:58 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		IPath root = project.getFolder("java").getLocation();
Нет, здесь можно любые классы java создавать

2017-11-17 10:06 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		IPath root = project.getFolder("java").getLocation();
Это понятно. Непонятно, зачем папка. Я же могу создавать java-классы в любом месте.

2017-11-17 10:14 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		IPath root = project.getFolder("java").getLocation();
![capture](https://user-images.githubusercontent.com/6087009/32942011-bf0d8862-cb98-11e7-80fe-fde0a94e3d79.PNG)
Здесь "java" является папкой, внутри которой уже лежат исходники, а внутри нее уже можно в любом месте создавать классы

2017-11-17 10:15 UTC, mikhailmineev commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		IPath root = project.getFolder("java").getLocation();
Или вы имеете ввиду, что должна быть возможность саму папку java переименовывать?

2017-11-17 10:27 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/execution/BuildUtil.java
> +		IPath root = project.getFolder("java").getLocation();
Например, переименовать. Если это не просто для красоты, то это костыль. Насколько я помню, ты костыльность подтвердил на консультации.

2017-11-18 10:48 UTC, aurusov commented on ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/console/ConsoleView.java
> +							synchronized (lock) {
Обсудили голосом - надо перейти на механизм счетчика.

2017-11-18 11:03 UTC, aurusov commented on ru.bmstu.rk9.rao.querydsl/pom.xml
> +		<version>3.9.0</version>
Есть [скрипт](https://github.com/aurusov/raox/blob/release/current/gitflow.md#Именование-бранчей), который обновляет версии. Надо убедиться, что эта версия тоже будет обновляться.

2017-12-07 22:38 UTC, mikhailmineev commented
У меня нет представления, почему перестал проект собираться

2018-12-24 22:28 UTC, mikhailmineev commented
Закрываю, после обсуждения с @LeKaitoW решено воссоздать отдельные пулреквесты для каждых фич, а для проекта у себя держать смерженую

2018-12-24 22:28 UTC, closed without merging